album/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.album, name='album'),
    url(r'^edit/(?P<album_id>\d+)/$', views.album_edit, name='edit'),
    url(r'^add/$', views.album_edit, name='add'),
    url(r'^photo_upload/$', views.album_photoupload, name='photoupload'),
    url(r'^photo_remove/(?P<photo_id>\d+)/$', views.album_photoremove, name='photoremove'),
    url(r'^wall/$', views.wall, name='wall'),
]

extuser/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.profile_edit, name='profile_edit'),
    url(r'^auth/$', views.auth_login, name='login'),
    url(r'^logout/$', views.auth_logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^user_create/$', views.user_create, name='user_create'),
    url(r'^avatar/$', views.change_avatar, name='avatar'),
    url(r'^upload_avatar/$', views.upload_avatar, name='upload_avatar'),
    url(r'^user_filter/$', views.user_filter, name='user_filter'),
    url(r'^reset_password/(?P<user_id>\d+)/$', views.reset_password, name='reset_password'),
    url(r'^user_delete/(?P<user_id>\d+)/$', views.user_delete, name='user_delete'),
]

faq/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^main/$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_edit, name='post_create'),
    url(r'^edit/(?P<post_id>\d+)/$', views.post_edit, name='post_edit'),
    url(r'^detail/(?P<post_id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^send_comment/(?P<post_id>\d+)/$', views.send_comment, name='send_comment'),
    url(r'^post_remove/(?P<post_id>\d+)/$', views.post_remove, name='post_remove'),
    url(r'^comment_remove/(?P<comment_id>\d+)/$', views.comment_remove, name='comment_remove'),
    url(r'^comment_update/$', views.comment_update, name='comment_update'),
    url(r'^menu_list/$', views.menu_list, name='menu_list'),
    url(r'^menu_create/$', views.menu_edit, name='menu_create'),
    url(r'^menu_edit/(?P<menu_id>\d+)/$', views.menu_edit, name='menu_edit'),
    url(r'^menu_remove/(?P<menu_id>\d+)/$', views.menu_remove, name='menu_remove'),
    url(r'^get_comment_text/$', views.get_comment_text, name='get_comment_text'),
]

tequilla/urls.py
from django.conf.urls import url, include
from django.http import HttpResponse

from tequilla import settings
from wall.views import index
from extuser.views import user_list, user_detail, user_activity, user_edit
from club.views import club_list
from album.views import user_albums

urlpatterns = [
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    url(r'^profile/', include('extuser.urls', namespace='profile')),
    url(r'^wall/', include('wall.urls', namespace='wall')),
    url(r'^clubs/', include('club.urls', namespace='club')),
    url(r'^album/', include('album.urls', namespace='album')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^tasks/', include('work_calendar.urls', namespace='calendar')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^faq/', include('faq.urls', namespace='faq')),
    url(r'^penalty/', include('penalty.urls', namespace='penalty')),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^uniform/', include('uniform.urls', namespace='uniform')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
    url(r'^statement/', include('statement.urls', namespace='statement')),
    url(r'^weekplan/', include('week_plan.urls', namespace='week_plan')),
    url(r'^dialog/', include('private_message.urls', namespace='pm')),
    url(r'^calculator/', include('calculator.urls', namespace='calc')),
    url(r'^employee/(?P<user_id>\d+)/', user_detail, name='user_detail'),
    url(r'^employee/album/(?P<user_id>\d+)/', user_albums, name='user_albums'),
    url(r'^employee/edit/(?P<user_id>\d+)/', user_edit, name='user_edit'),
    url(r'^employee/auth/(?P<user_id>\d+)/', user_activity, name='user_activity'),
    url(r'^employee/', user_list, name='user_list'),
    url(r'^$', index, name='wall_index'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

extuser/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group

from club.models import Club
from extuser.models import ExtUser


class UserImportForm(forms.ModelForm):
    """
    Форма добавления пользователя
    """

    def save(self, commit=True):
        user = super(UserImportForm, self).save(commit=False)
        user.set_password('secret' + str(self.cleaned_data['old_id']))
        if commit:
            user.save()

        return user

    class Meta:
        model = ExtUser
        exclude = ('avatar', 'password')


class ChangeAvatarForm(forms.ModelForm):
    """
    Форма загрузки нового аватара
    """

    class Meta:
        model = ExtUser
        fields = ('avatar',)


class UserCreationForm(forms.ModelForm):
    """
    Форма добавления пользователя которая используется на странице регистрации
    """
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'})
    )
    confirm_password = forms.CharField(
        label='Подтверждение пароля',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтверждение пароля'})
    )

    class Meta:

        model = ExtUser

        # Note - include all *required* MyUser fields here,
        # but don't need to include password and confirm_password as they are
        # already included since they are defined above.
        fields = ('surname', 'name', 'email', 'phone', 'vkontakte')

        widgets = {
            'surname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Фамилия', 'required': True}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя', 'required': True}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'E-mail', 'required': True}),
            'phone': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Мобильный телефон (Без +7 и 8)', 'required': True}
            ),
            'vkontakte': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'id Вконтакте'}),
        }

    def clean(self):
        if 'confirm_password' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
                self.add_error('confirm_password', 'Введённые пароли не совпадают')
        # email обязательное поле
        if 'email' not in self.cleaned_data or not self.cleaned_data['email']:
            self.add_error('email', 'Обязательное поле')

        return super().clean()

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()

        return user


class UserEditAdminForm(forms.ModelForm):
    """
    Форма для редактирования данных пользователей.
    Используется РУКОВОДСТВОМ для редактирования данных сотрудников.
    """
    group = forms.ModelChoiceField(queryset=Group.objects.all(), required=True, label='Роль')
    clubs = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        queryset=Club.objects.filter(is_active=True),
        label='Заведения',
        required=False
    )

    def __init__(self, *args, **kwargs):
        super(UserEditAdminForm, self).__init__(*args, **kwargs)
        # запретить возможность выбора директора
        if self.instance and self.instance.pk:
            current_group = self.instance.groups.get()
            self.fields['group'].initial = current_group.pk
            self.fields['clubs'].initial = [t.pk for t in self.instance.clubs.all()]

    def save(self, commit=True):
        if self.instance and self.instance.id:
            # сохранение новой группы
            self.instance.groups.clear()
            self.instance.groups.add(self['group'].value())

            # клубы
            self.instance.clubs.clear()
            for club in self['clubs'].value():
                self.instance.clubs.add(club)

        return super(UserEditAdminForm, self).save(commit)

    class Meta:
        model = get_user_model()
        fields = ('surname', 'name', 'gender', 'email', 'phone', 'additional_phone', 'group',
                  'vkontakte', 'pledge', 'coordinator', 'pay_to_coord', 'is_active', 'clubs')


class UserChangeForm(forms.ModelForm):
    """
    Форма для обновления данных пользователей.
    Форма используется для редактирования собственных данных.
    """

    def save(self, commit=True):
        user = super(UserChangeForm, self).save(commit=False)
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ('surname', 'name', 'gender', 'email', 'phone', 'vkontakte')

        classes = 'form-control col-md-7 col-xs-12'
        widgets = {
            'surname': forms.TextInput(
                attrs={'class': classes, 'required': True, 'data-parsley-id': '1'}
            ),
            'name': forms.TextInput(
                attrs={'class': classes, 'required': True, 'data-parsley-id': '2'}
            ),
            'gender': forms.Select(
                attrs={'class': classes, 'required': True, 'data-parsley-id': '3'}
            ),
            'email': forms.EmailInput(
                attrs={'class': classes, 'data-parsley-id': '4'}
            ),
            'phone': forms.TextInput(
                attrs={'class': classes, 'required': True, 'data-parsley-id': '5'}
            ),
            'vkontakte': forms.TextInput(
                attrs={'class': classes, 'data-parsley-id': '6'}
            ),
        }


class LoginForm(forms.Form):
    """
    Форма для входа в систему
    """
    phone = forms.CharField(
        label='Номер телефона',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Номер телефона'})
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'})
    )


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(
        label='Текущий пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Текущий пароль', 'required': True})
    )
    new_password = forms.CharField(
        label='Новый пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Новый пароль', 'required': True})
    )
    confirm_password = forms.CharField(
        label='Повторите пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Повторите пароль', 'required': True})
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean_current_password(self):
        valid = self.user.check_password(self.cleaned_data['current_password'])
        if not valid:
            self.add_error('current_password', "Неверный текущий пароль.")
        return valid

    def clean(self):
        if 'new_password' in self.cleaned_data:
            if 'confirm_password' in self.cleaned_data:
                if self.cleaned_data['new_password'] != self.cleaned_data['confirm_password']:
                    self.add_error('confirm_password', 'Введённые пароли не совпадают')
            else:
                self.add_error('confirm_password', 'Обязательное поле')
        else:
            self.add_error('new_password', 'Обязательное поле')
        return super().clean()

album/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse

from extuser.models import ExtUser
from tequilla import settings
from tequilla.decorators import group_required
from .models import Album, Photo


@login_required
def album(request):
    object_list = request.user.albums.all()
    is_director = request.user.groups.filter(name='director').exists()
    paginator = Paginator(object_list, (settings.ALBUMS_COUNT_ON_WALL - 1) if is_director else settings.ALBUMS_COUNT_ON_WALL)
    page = request.GET.get('page')
    try:
        albums = paginator.page(page)
    except PageNotAnInteger:
        albums = paginator.page(1)
    except EmptyPage:
        albums = paginator.page(paginator.num_pages)
    return render(
        request,
        'album/album.html',
        {'albums': albums}
    )


@login_required
def album_edit(request, album_id=None):
    if request.is_ajax() and request.method == 'POST':
        if album_id:
            album = Album.objects.get(id=album_id)
            if request.POST['name']:
                album.name = request.POST['name']
            album.save()
        else:
            album = Album.objects.create(name=request.POST['name'], user=request.user)

        photo_ids = request.POST.getlist('new_photos[]', [])
        if photo_ids:
            Photo.objects.filter(id__in=photo_ids).update(album=album)
        return JsonResponse({
            'link': 'http://' + request.get_host() + reverse('album:edit', kwargs={'album_id': album.id})
        })
    album = Album.objects.get(id=album_id) if album_id else Album()
    return render(
        request,
        'album/album_edit.html',
        {'album': album}
    )


@login_required
@csrf_exempt
def album_photoupload(request):
    result = []
    images = request.FILES.getlist('files[]', [])
    for image in images:
        image_obj = Photo.objects.create(file=image, user=request.user)
        result.append({
            'id': image_obj.id,
            'url': image_obj.file.url,
            'remove_link': reverse('album:photoremove', kwargs={'photo_id': image_obj.id})
        })
    return JsonResponse({'images': result})


@login_required
@csrf_exempt
def album_photoremove(request, photo_id):
    try:
        Photo.objects.get(id=photo_id, user=request.user).delete()
        return JsonResponse({'complete': 1})
    except Photo.DoesNotExist:
        return JsonResponse({'complete': 0})


@login_required
def wall(request):
    if 'callback' in request.GET:
        object_list = Album.objects
        filters = ['user', 'created__lte', 'created__gte']
        was_filtered = False
        for filter_name in filters:
            filter_value = request.GET.get(filter_name, 0)
            if filter_value:
                filter_pack = {filter_name: filter_value}
                object_list = object_list.filter(**filter_pack)
                was_filtered = True
        if 'user__is_active' in request.GET:
            object_list = object_list.filter(user__is_active=(request.GET['user__is_active'] == 'True'))
        if not was_filtered:
            object_list = object_list.all()
    else:
        object_list = Album.objects.all()

    paginator = Paginator(object_list, settings.ALBUMS_COUNT_ON_WALL)
    page = request.GET.get('page')
    try:
        albums = paginator.page(page)
    except PageNotAnInteger:
        albums = paginator.page(1)
    except EmptyPage:
        albums = paginator.page(paginator.num_pages)

    # если ajax запрос отрендерить блоки с навигацией и новые пагинаторы
    if 'callback' in request.GET:
        rendered_blocks = {
            'albums': render_to_string('album/_wall_part.html', {'albums': albums}),
            'paginator': render_to_string('pagination.html', {'page': albums})
        }
        data = '%s(%s);' % (request.GET['callback'], json.dumps(rendered_blocks))
        return HttpResponse(data, "text/javascript")

    return render(
        request,
        'album/wall.html',
        {
            'albums': albums,
            'users': ExtUser.objects.order_by('surname'),
            'filter_link': reverse('album:wall')
        }
    )


# просмотр альбома руководством
@login_required
@group_required('director', 'chief', 'coordinator')
def user_albums(request, user_id):
    user = get_object_or_404(ExtUser, id=user_id)
    return render(
        request,
        'album/user_albums.html',
        {'user_info': user}
    )

extuser/templates/profile/album.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Мои фотоотчеты{% endblock %}
{% block content %}
    <div class="row">
        <a href="{% url 'profile:album_add' %}"><button class="btn btn-success"><i class="fa fa-plus"></i> Добавить новый фотоотчет</button></a>
        {% for album in user.albums.all %}
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>{{ album.name }}
                            <small>Дата создания фотоотчета: {{ album.created }}</small>
                        </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a style="font-size: 17px;" href="{% url 'profile:album_edit' album.id %}"><i class="fa fa-edit"></i></a></li>
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="thumbnails"  data-post-id="{{ album.id }}">
                            {% for photo in album.photos.all %}
                                <div class="thumbnail margin-right">
                                    <div class="image">
                                         {% thumbnail photo.file "140x100" as im %}
                                            <a class="group-{{ album.id }}" href="{{ photo.file.url }}">
                                                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                                            </a>
                                        {% endthumbnail %}
                                    </div>
                                </div>
                            {% empty %}
                                В этот фотоотчет еще не были загружены фотографии.
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

extuser/templates/profile/change_avatar.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Аватар{% endblock %}
{% block additional_js %}
    <!-- image cropping -->
    <script src="{% static 'js/cropping/cropper.js' %}"></script>
    <script src="{% static 'js/cropping/custom-crop.js' %}"></script>
{% endblock %}

{% block additional_css %}
    <link href="/media/temp/cropper.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/lleo.css' %}">
    <style>
    img {
          max-width: 100%; /* This rule is very important, please do not ignore this! */
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row avatar">
        <div class="container cropper">
            <div class="row">
                <div class="col-md-9">
                    <div class="img-container">
                        {% if user.avatar %}
                            <img id="image" src="{{ user.avatar.url }}{% comment %}/media/temp/picture2.jpg{% endcomment %}" alt="Picture">
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>
         <button id="super-button" class="btn btn-info">Сохранить маленький аватар</button>
        <hr>
        <h3>Загрузить другую фотографию</h3>
        <form action="." method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" class="btn btn-warning" name="avatar">
            <input type="submit" class="btn btn-success" value="Сохранить новую фотографию">
        </form>
        <hr>
    </div>
{% endblock %}

extuser/templates/profile/change_password.html
{% extends 'base.html' %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Смена пароля
                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>
                    <form data-parsley-validate="" class="form-horizontal form-label-left" method="POST" action="{% url 'profile:change_password' %}">
                        {% if messages %}
                            <p class="alert alert-success fade in">
                                {% for message in messages %}
                                    <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span><br>
                                {% endfor %}
                            </p>
                        {% endif %}
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group{% if field.errors %} bad{% endif %}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                                {{ field.label }} {% if field.field.required %}<span class="required">*</span>{% endif %}
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ field }}
                                {% if field.errors %}
                                    <ul class="parsley-errors-list" id="parsley-id-{{ forloop.counter }}">
                                         {% for error in field.errors %}
                                            <li>{{ error|escape }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

extuser/templates/profile/edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Личный кабинет
                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>
                    <form data-parsley-validate="" class="form-horizontal form-label-left" method="POST" action="{% url 'profile:profile_edit' %}">
                        {% if messages %}
                            <p class="alert alert-success fade in">
                                {% for message in messages %}
                                    <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span><br>
                                {% endfor %}
                            </p>
                        {% endif %}
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group{% if field.errors %} bad{% endif %}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                                {{ field.label }} {% if field.field.required %}<span class="required">*</span>{% endif %}
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ field }}
                                {% if field.errors %}
                                    <ul class="parsley-errors-list" id="parsley-id-{{ forloop.counter }}">
                                         {% for error in field.errors %}
                                            <li>{{ error|escape }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

extuser/templates/profile/login.html
{% extends 'base.html' %}
{% block title %}Авторизация{% endblock %}
{% block content %}
    <style type="text/css">
        body.nav-md .container.body .right_col {
            padding: 0 !important;
            margin-left: 0 !important;
        }
    </style>
    <div class="">
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>

        <div id="wrapper">
            <div id="login" class="animate form">
                <section class="login_content">
                    <form method="POST" action="{% url 'profile:login' %}" id="login-form">
                        {% csrf_token %}
                        <h1>Авторизация</h1>
                        {% if error %}
                            <p class="parsley-error">Неверный номер телефона или пароль</p>
                        {% endif %}
                        <div>
                            {{ login_form.phone }}
                        </div>
                        <div>
                            {{ login_form.password }}
                        </div>

                        <div>
                            <a class="btn btn-default submit" onclick="document.getElementById('login-form').submit()">Войти</a>
                        </div>
                        <div class="clearfix"></div>
                        <div class="separator">

                            <p class="change_link">
                                <a href="#toregister" class="to_register"> Зарегистрироваться </a>
                            </p>
                            <div class="clearfix"></div>
                        </div>
                    </form>
                    <!-- form -->
                </section>
                <!-- content -->
            </div>
            <div id="register" class="animate form">
                <section class="login_content">
                    {% if not registered %}
                        <form method="POST" action="{% url 'profile:register' %}#toregister" id="register-form">
                            {% csrf_token %}
                            <h1>Регистрация</h1>
                            {% for field in register_form %}
                                <div{% if field.errors %} class="bad"{% endif %}>
                                    {% if field.errors %}
                                        <p class="parsley-error">
                                            {% for error in field.errors %}
                                                <strong>{{ error|escape }}</strong><br>
                                            {% endfor %}
                                        </p>
                                    {% endif %}
                                    {{ field }}
                                </div>
                            {% endfor %}

                            <div>
                                <a class="btn btn-default submit" onclick="document.getElementById('register-form').submit()">Зарегистрироваться</a>
                            </div>
                            <div class="clearfix"></div>
                            <div class="separator">

                                <p class="change_link">Уже зарегистрированы?
                                    <a href="#tologin" class="to_register"> Войти </a>
                                </p>
                                <div class="clearfix"></div>
                            </div>
                        </form>
                        <!-- form -->
                    {% else %}
                        Вы успешно зарегистрировались, ожидайте когда вашу заявку подтвердят.
                    {% endif %}
                </section>
                <!-- content -->
            </div>
        </div>
    </div>
{% endblock %}