faq/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^main/$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_edit, name='post_create'),
    url(r'^edit/(?P<post_id>\d+)/$', views.post_edit, name='post_edit'),
    url(r'^detail/(?P<post_id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^send_comment/(?P<post_id>\d+)/$', views.send_comment, name='send_comment'),
    url(r'^post_remove/(?P<post_id>\d+)/$', views.post_remove, name='post_remove'),
    url(r'^comment_remove/(?P<comment_id>\d+)/$', views.comment_remove, name='comment_remove'),
    url(r'^comment_update/$', views.comment_update, name='comment_update'),
    url(r'^menu_list/$', views.menu_list, name='menu_list'),
    url(r'^menu_create/$', views.menu_edit, name='menu_create'),
    url(r'^menu_edit/(?P<menu_id>\d+)/$', views.menu_edit, name='menu_edit'),
    url(r'^menu_remove/(?P<menu_id>\d+)/$', views.menu_remove, name='menu_remove'),
    url(r'^get_comment_text/$', views.get_comment_text, name='get_comment_text'),
]

tequilla/urls.py
from django.conf.urls import url, include
from django.http import HttpResponse

from tequilla import settings
from wall.views import index
from extuser.views import user_list, user_detail, user_activity, user_edit
from club.views import club_list
from album.views import user_albums

urlpatterns = [
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    url(r'^profile/', include('extuser.urls', namespace='profile')),
    url(r'^wall/', include('wall.urls', namespace='wall')),
    url(r'^clubs/', include('club.urls', namespace='club')),
    url(r'^album/', include('album.urls', namespace='album')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^tasks/', include('work_calendar.urls', namespace='calendar')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^faq/', include('faq.urls', namespace='faq')),
    url(r'^penalty/', include('penalty.urls', namespace='penalty')),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^uniform/', include('uniform.urls', namespace='uniform')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
    url(r'^statement/', include('statement.urls', namespace='statement')),
    url(r'^weekplan/', include('week_plan.urls', namespace='week_plan')),
    url(r'^dialog/', include('private_message.urls', namespace='pm')),
    url(r'^calculator/', include('calculator.urls', namespace='calc')),
    url(r'^employee/(?P<user_id>\d+)/', user_detail, name='user_detail'),
    url(r'^employee/album/(?P<user_id>\d+)/', user_albums, name='user_albums'),
    url(r'^employee/edit/(?P<user_id>\d+)/', user_edit, name='user_edit'),
    url(r'^employee/auth/(?P<user_id>\d+)/', user_activity, name='user_activity'),
    url(r'^employee/', user_list, name='user_list'),
    url(r'^$', index, name='wall_index'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

faq/models.py
import os
import random

from django.db import models
from model_utils.models import TimeStampedModel
from sorl.thumbnail import ImageField

from extuser.models import ExtUser


class Post(TimeStampedModel):
    name = models.CharField('Название', max_length=255)
    description = models.TextField('Краткое описание')
    content = models.TextField('Содержимое')
    old_id = models.PositiveIntegerField('ID из старой системы', blank=True, null=True)

    def __str__(self):
        return self.name


class Comment(TimeStampedModel):
    post = models.ForeignKey(Post, related_name='comments')
    employee = models.ForeignKey(ExtUser)
    content = models.TextField('Комментарий')
    parent = models.ForeignKey('self', related_name='childrens', blank=True, null=True)
    old_id = models.PositiveIntegerField('ID из старой системы', blank=True, null=True)

    def __str__(self):
        return self.content[:50]

    class Meta:
        ordering = ('-created',)


class CommentPhoto(TimeStampedModel):
    def get_upload_path(self, filename):
        slug = str(self.post.id)
        return os.path.join('faq_comment_img', '%s' % slug, str(random.randint(1, 1000000)) + '_' + filename)

    file = ImageField(upload_to=get_upload_path, verbose_name='Изображение')
    post = models.ForeignKey(Comment, related_name='images')


class Menu(TimeStampedModel):
    name = models.CharField('Название', max_length=255)
    parent = models.ForeignKey(
        'self', related_name='childrens', blank=True, null=True, verbose_name='Родительское меню'
    )
    post = models.ForeignKey(
        Post, verbose_name='Привязка к записи', blank=True, null=True
    )
    order = models.SmallIntegerField(verbose_name='Сортировка', default=0)

    class Meta:
        ordering = ('order',)

    def __str__(self):
        return self.name

faq/forms.py
from django import forms
from django.db.models import Q

from .models import Post, Comment, Menu


class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('name', 'description', 'content')


class MenuEditForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('name', 'parent', 'post', 'order')

    def __init__(self, *args, **kwargs):
        super(MenuEditForm, self).__init__(*args, **kwargs)
        self.fields['parent'].queryset = Menu.objects.exclude(
            Q(id__exact=self.instance.id) | Q(parent__isnull=False))


class CommentAddForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', 'parent')

faq/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from faq.forms import PostEditForm, CommentAddForm, MenuEditForm
from faq.models import Post, Comment, Menu, CommentPhoto
from tequilla.decorators import group_required


@login_required
@group_required('director', 'chief', 'coordinator')
def post_list(request):
    return render(request, 'faq/post_list.html', {'posts': Post.objects.all()})


@login_required
@group_required('director', 'chief', 'coordinator')
def post_edit(request, post_id=None):
    try:
        post = Post.objects.get(id=post_id)
    except Post.DoesNotExist:
        post = None

    if request.method == 'POST':
        form = PostEditForm(data=request.POST) if post is None else PostEditForm(instance=post, data=request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('faq:post_detail', post_id=post.id)
    else:
        form = PostEditForm() if post is None else PostEditForm(instance=post)
    return render(
        request,
        'faq/post_edit.html',
        {'form': form, 'post': post}
    )


@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(
        request,
        'faq/post_detail.html',
        {'post': post, 'comments': Comment.objects.filter(parent__isnull=True, post=post.id)}
    )


@login_required
@require_POST
def send_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentAddForm(data=request.POST)
    images = request.FILES.getlist('images[]', [])
    if form.is_valid():
        cd = form.cleaned_data
        data = {'post': post, 'employee': request.user}
        data.update(cd)
        comment = Comment.objects.create(**data)

        for image in images:
            photo_object = CommentPhoto(file=image, post=comment)
            photo_object.save()
    else:
        print(form.errors)
    return redirect('faq:post_detail', post_id=post.id)


@login_required
@group_required('director', 'chief', 'coordinator')
def post_remove(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect('faq:post_list')


@login_required
@group_required('director', 'chief', 'coordinator')
def comment_remove(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.employee == request.user or request.user.groups.filter(name='director').exists():
        comment.delete()
    return redirect('faq:post_detail', post_id=comment.post.id)


@login_required
@group_required('director', 'chief', 'coordinator')
def menu_list(request):
    return render(request, 'menu/list.html', {'items': Menu.objects.all()})


@login_required
@group_required('director', 'chief', 'coordinator')
def menu_edit(request, menu_id=None):
    try:
        menu = Menu.objects.get(id=menu_id)
    except Menu.DoesNotExist:
        menu = None

    if request.method == 'POST':
        form = MenuEditForm(data=request.POST) if menu is None else MenuEditForm(instance=menu, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('faq:menu_list')
    else:
        form = MenuEditForm() if menu is None else MenuEditForm(instance=menu)
    return render(
        request,
        'menu/edit.html',
        {
            'form': form,
            'menu': menu
        }
    )


@login_required
@group_required('director', 'chief', 'coordinator')
def menu_remove(request, menu_id):
    menu = get_object_or_404(Menu, id=menu_id)
    menu.delete()
    return redirect('faq:menu_list')


@login_required
@require_POST
@csrf_exempt
def comment_update(request):
    post = get_object_or_404(Comment, id=request.POST.get('id', 0))
    if post.employee == request.user or request.user.groups.filter(name__in=['director', 'chief', 'coordinator']).exists():
        post.content = request.POST.get('text', '')
        post.save()
    return redirect('faq:post_detail', post_id=request.POST.get('faq_id', 0))


@login_required
def get_comment_text(request):
    post = get_object_or_404(Comment, id=request.GET.get('id', 0))
    return JsonResponse({'text': post.content})

faq/templates/faq/post_edit.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    {% if post %}
        Редактирование статьи {{ post.name }}
    {% else %}
        Добавление новой статьи
    {% endif %}
{% endblock %}

{% block additional_css %}
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.css" rel="stylesheet">
{% endblock %}

{% block additional_js %}
    <!-- include summernote js-->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.js"></script>
    <script src="{% static 'js/summernote-ru-RU.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('input, textarea').not(':checkbox').addClass('form-control');

            $('#id_content').summernote({
                height: 200,
                lang: 'ru-RU',
                dialogsInBody: false,
                dialogsFade: false,
                iframe: false

            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        {% if post %}
                            Редактирование статьи {{ post.name }}
                        {% else %}
                            Добавление новой статьи
                        {% endif %}
                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    {% if messages %}
                        <p class="alert alert-success fade in">
                            {% for message in messages %}
                                <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span><br>
                            {% endfor %}
                        </p>
                    {% endif %}
                    <form method="POST"
                          id="edit-user-form"
                          data-parsley-validate=""
                          class="form-horizontal form-label-left"
                          action="{% if post %}{% url 'faq:post_edit' post.id %}{% else %}{% url 'faq:post_create' %}{% endif %}">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group{% if field.errors %} bad{% endif %}">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                                    {{ field.label }} {% if field.field.required %}
                                    <span class="required">*</span>{% endif %}
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ field }}
                                    {% if field.errors %}
                                        <ul class="parsley-errors-list" id="parsley-id-{{ forloop.counter }}">
                                            {% for error in field.errors %}
                                                <li>{{ error|escape }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

faq/templates/faq/post_list.html
{% extends 'base.html' %}

{% block title %}FAQ{% endblock %}

{% block additional_js %}
    <script type="text/javascript">
        $(function() {
            $('.remove-link').on('click', function() {
                return confirm('Подтвердите удаление');
            });
        });
    </script>
{% endblock %}

{% block content %}
    <h1>Статьи</h1>
    <a href="{% url 'faq:post_create' %}" class="btn btn-info">Добавить статью</a>
    {% for post in posts %}
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><a href="{% url 'faq:post_detail' post.id %}"><i class="fa fa-book"></i> {{ post.name }}</a></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a href="{% url 'faq:post_detail' post.id %}"><i class="fa fa-open"></i>Открыть</a></li>
                        <li><a href="{% url 'faq:post_edit' post.id %}">Редактировать</a></li>
                        <li><a class="remove-link" href="{% url 'faq:post_remove' post.id %}">Удалить</a></li>
                        <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    {{ post.description }}
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}