faq/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^main/$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_edit, name='post_create'),
    url(r'^edit/(?P<post_id>\d+)/$', views.post_edit, name='post_edit'),
    url(r'^detail/(?P<post_id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^send_comment/(?P<post_id>\d+)/$', views.send_comment, name='send_comment'),
    url(r'^post_remove/(?P<post_id>\d+)/$', views.post_remove, name='post_remove'),
    url(r'^comment_remove/(?P<comment_id>\d+)/$', views.comment_remove, name='comment_remove'),
    url(r'^comment_update/$', views.comment_update, name='comment_update'),
    url(r'^menu_list/$', views.menu_list, name='menu_list'),
    url(r'^menu_create/$', views.menu_edit, name='menu_create'),
    url(r'^menu_edit/(?P<menu_id>\d+)/$', views.menu_edit, name='menu_edit'),
    url(r'^menu_remove/(?P<menu_id>\d+)/$', views.menu_remove, name='menu_remove'),
    url(r'^get_comment_text/$', views.get_comment_text, name='get_comment_text'),
]

statement/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.statement_by_week, name='statement_by_week'),
    url(r'^show/(?P<week>[\d\-]+)/(?P<start_date>([\d\-])+)/$', views.show, name='statement_show'),
    url(r'^export_xls/(?P<week>[\d\-]+)/(?P<start_date>([\d\-])+)/$', views.export_xls, name='export_xls'),
]

tequilla/urls.py
from django.conf.urls import url, include
from django.http import HttpResponse

from tequilla import settings
from wall.views import index
from extuser.views import user_list, user_detail, user_activity, user_edit
from club.views import club_list
from album.views import user_albums

urlpatterns = [
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    url(r'^profile/', include('extuser.urls', namespace='profile')),
    url(r'^wall/', include('wall.urls', namespace='wall')),
    url(r'^clubs/', include('club.urls', namespace='club')),
    url(r'^album/', include('album.urls', namespace='album')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^tasks/', include('work_calendar.urls', namespace='calendar')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^faq/', include('faq.urls', namespace='faq')),
    url(r'^penalty/', include('penalty.urls', namespace='penalty')),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^uniform/', include('uniform.urls', namespace='uniform')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
    url(r'^statement/', include('statement.urls', namespace='statement')),
    url(r'^weekplan/', include('week_plan.urls', namespace='week_plan')),
    url(r'^dialog/', include('private_message.urls', namespace='pm')),
    url(r'^calculator/', include('calculator.urls', namespace='calc')),
    url(r'^employee/(?P<user_id>\d+)/', user_detail, name='user_detail'),
    url(r'^employee/album/(?P<user_id>\d+)/', user_albums, name='user_albums'),
    url(r'^employee/edit/(?P<user_id>\d+)/', user_edit, name='user_edit'),
    url(r'^employee/auth/(?P<user_id>\d+)/', user_activity, name='user_activity'),
    url(r'^employee/', user_list, name='user_list'),
    url(r'^$', index, name='wall_index'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

statement/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import formats
from django.utils.dateparse import parse_date
from xlwt.compat import xrange

from club.models import City
from statement.utils import get_statement_data, Writer
from tequilla.decorators import group_required


@login_required
@group_required('director', 'chief')
def statement_by_week(request):
    week_offset = int(request.GET.get('week', 0))
    start_date = parse_date(request.GET.get('start_date', str(datetime.date.today())))
    date = start_date + datetime.timedelta(week_offset * 7)
    start_week = date - datetime.timedelta(date.weekday())
    end_week = start_week + datetime.timedelta(6)

    return render(
        request,
        'statement/index.html',
        {
            'start_week': start_week,
            'end_week': end_week,
            'next_week': week_offset + 1,
            'prev_week': week_offset - 1,
            'start_date': formats.date_format(start_date, 'Y-m-d'),
            'week_offset': week_offset,
            'cities': City.objects.all()
        }
    )


@login_required
@group_required('director')
def show(request, week, start_date):
    available_filters = ['city', 'only_users']
    enabled_filters = {}
    for f in available_filters:
        if f in request.GET:
            enabled_filters[f] = request.GET.get(f, None)
    return render(
        request,
        'statement/show.html',
        get_statement_data(week, start_date, enabled_filters)
    )


@login_required
@group_required('director')
def export_xls(request, week, start_date):
    import xlwt
    data = get_statement_data(week, start_date)

    file_name = 'statement({} {}).xls'.format(data['start_week'], data['end_week'])
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=' + file_name
    wb = xlwt.Workbook(encoding='utf-8')

    # кастомные цвета
    xlwt.add_palette_colour("custom_blue", 0x21)
    wb.set_colour_RGB(0x21, 0, 176, 240)
    blue_style = xlwt.easyxf('pattern: pattern solid, fore_colour custom_blue')

    xlwt.add_palette_colour("custom_light_blue", 0x22)
    wb.set_colour_RGB(0x22, 146, 205, 220)
    light_blue_style = xlwt.easyxf('pattern: pattern solid, fore_colour custom_light_blue')

    xlwt.add_palette_colour("custom_orange", 0x23)
    wb.set_colour_RGB(0x23, 255, 192, 0)
    orange_style = xlwt.easyxf('pattern: pattern solid, fore_colour custom_orange')

    xlwt.add_palette_colour("custom_light_green", 0x24)
    wb.set_colour_RGB(0x24, 146, 208, 80)
    light_green_style = xlwt.easyxf('pattern: pattern solid, fore_colour custom_light_green')

    xlwt.add_palette_colour("custom_yellow", 0x25)
    wb.set_colour_RGB(0x25, 255, 255, 0)
    yellow_style = xlwt.easyxf('pattern: pattern solid, fore_colour custom_yellow')

    xlwt.add_palette_colour("custom_pink", 0x26)
    wb.set_colour_RGB(0x26, 230, 184, 183)
    pink_style = xlwt.easyxf('pattern: pattern solid, fore_colour custom_pink')

    xlwt.add_palette_colour("custom_dark_pink", 0x27)
    wb.set_colour_RGB(0x27, 218, 150, 148)
    dark_pink_style = xlwt.easyxf('pattern: pattern solid, fore_colour custom_dark_pink')

    xlwt.add_palette_colour("custom_penalty", 0x28)
    wb.set_colour_RGB(0x28, 218, 150, 148)
    penalty_style = xlwt.easyxf('pattern: pattern solid, fore_colour custom_penalty')

    xlwt.add_palette_colour("custom_purple", 0x29)
    wb.set_colour_RGB(0x29, 177, 160, 199)
    purple_style = xlwt.easyxf('pattern: pattern solid, fore_colour custom_purple')

    xlwt.add_palette_colour("custom_red", 0x30)
    wb.set_colour_RGB(0x30, 255, 71, 71)
    red_style = xlwt.easyxf('pattern: pattern solid, fore_colour custom_red')

    font_style_bold = xlwt.XFStyle()
    font_style_bold.font.bold = True

    writer = Writer(wb.add_sheet('statement'))
    # ws = wb.add_sheet('statement')#, cell_overwrite_ok=True)

    # ПЕРВАЯ СТРОКА
    font_style = xlwt.XFStyle()
    for i in xrange(len(data['drinks_table_header']) + 2):
        writer.write('', font_style)

    writer.write('Tequilla Girl', font_style_bold)
    # имена сотрудников
    for idx, employee in enumerate(data['employees_table_header']):
        writer.write('{}. {}'.format(idx + 1, employee.get_full_name()), font_style)

    # ВТОРАЯ СТРОКА
    writer.new_row()
    writer.write('', font_style)
    writer.write('', font_style)
    # названия напитков
    for drink_data in data['drinks_table_header']:
        if drink_data['used']:
            writer.write(drink_data['name'], font_style)

    writer.write('Менеджер Tequilla girl', font_style_bold)

    # координаторы
    for employee in data['employees_table_header']:
        text = employee.coordinator.get_full_name() if employee.coordinator else ''
        writer.write(text, font_style)

    # ТРЕТЬЯ СТРОКА
    writer.new_row()
    writer.write('Клуб', font_style_bold)
    writer.write('Менеджер клуба', font_style_bold)
    for drink_data in data['drinks_table_header']:
        if drink_data['used']:
            writer.write('Цена', font_style)
    writer.write('Напитки', font_style_bold)
    # названия напитков
    for drinks in data['header_drinks_for_employee'].values():
        names = [drink for drink in drinks]
        writer.write('{}, {}, {}'.format(', '.join(names), 'Всего клуб', 'Коорд-р'), font_style)

    # ВЫВОД ТАБЛИЦЫ
    for idx, row in enumerate(data['grid']):
        writer.new_row()
        writer.write(
            '{}. {} {}, {}'.format(
                idx + 1, row['club'].name, row['club'].get_address(), row['club'].city if row['club'].city else ''
            ),
            yellow_style if idx % 2 == 0 else orange_style
        )
        writer.write(row['club'].coordinator.surname if row['club'].coordinator else '', light_green_style)
        for ndx, price in enumerate(row['drinks_for_club']):
            if price['used']:
                writer.write(
                    price['sum'],
                    blue_style if ndx % 2 == 0 else light_blue_style
                )
        writer.write('', font_style)
        for info in row['employees_info']:
            count = [str(drink['count']) for drink in info['drinks_list']]
            writer.write(
                '{}, {:.2f}р., {:.2f}р.'.format(' '.join(count), info['sum_for_club'], info['sum_for_coordinator']),
                yellow_style
            )

    # ФУТЕР
    writer.new_row()
    writer.write('ВСЕГО (Перевод Tequilla girl)', pink_style)
    for i in xrange(len(data['drinks_table_header']) + 2):
        writer.write('', pink_style)
    for info in data['bottom_prices_for_employee'].values():
        writer.write('{:.2f}'.format(info['all']), pink_style)

    writer.new_row()
    writer.write('Залог Tequilla girl', dark_pink_style)
    for i in xrange(len(data['drinks_table_header']) + 2):
        writer.write('', dark_pink_style)
    for info in data['bottom_prices_for_employee'].values():
        writer.write(info['pledge'], dark_pink_style)

    writer.new_row()
    writer.write('Штраф', penalty_style)
    for i in xrange(len(data['drinks_table_header']) + 2):
        writer.write('', penalty_style)
    for info in data['bottom_prices_for_employee'].values():
        writer.write('{:.2f}'.format(info['penalty']), penalty_style)

    writer.new_row()
    writer.write('Причина штрафа', penalty_style)
    for i in xrange(len(data['drinks_table_header']) + 2):
        writer.write('', penalty_style)
    for info in data['bottom_prices_for_employee'].values():
        description = [description for description in info['penalty_description']]
        writer.write('; '.join(description), penalty_style)

    writer.new_row()
    writer.write('Координатор (всего за клубы по каждой Tequilla Girl)', purple_style)
    for i in xrange(len(data['drinks_table_header']) + 2):
        writer.write('', purple_style)
    for info in data['bottom_prices_for_employee'].values():
        writer.write('{:.2f}'.format(info['coordinator']), purple_style)

    writer.new_row()
    writer.write('Ермакова (всего за клубы по каждой Tequilla Girl)', light_blue_style)
    for i in xrange(len(data['drinks_table_header']) + 2):
        writer.write('', light_blue_style)
    for info in data['bottom_prices_for_employee'].values():
        writer.write('{:.2f}'.format(info['director']), light_blue_style)

    writer.new_row()
    writer.new_row()
    for coordinator, salary in data['admins_salary']['coordinators'].items():
        writer.write(
            'Координатор {}(за все клубы и за всех tequila girls): {:.2f}'.format(coordinator.get_full_name(), salary),
            pink_style
        )
        writer.new_row()

    writer.write(
        'Ермакова(за все клубы и за всех tequila girls): {:.2f}'.format(data['admins_salary']['director']),
        red_style
    )

    wb.save(response)
    return response

statement/templates/statement/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Ведомость{% endblock %}

{% block additional_js %}
    <script>
        $(function() {
            setCalendarForButton('');
        });
    </script>
{% endblock %}

{% block content %}
    <div class="col-md-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Ведомость
                    <small>{{ start_week }} - {{ end_week }}</small>
                </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <!-- buttons start -->
                <a href="?week={{ prev_week }}&start_date={{ start_date }}">
                    <button class="btn"><i class="fa fa-long-arrow-left"></i> Предыдущая неделя</button>
                </a>
                <a href="?week={{ next_week }}&start_date={{ start_date }}">
                    <button class="btn">Следующая неделя <i class="fa fa-long-arrow-right"></i></button>
                </a>
                <div class="small-margin-top">
                    <button class="btn btn-primary" id="calendar">Выбрать неделю по дате</button>
                </div>
                <hr>
                <div class="small-margin-top">
                    <a class="btn btn-success btn-statement"
                       href="{% url 'statement:statement_show' week_offset start_date %}">Показать</a>
                    {% for city in cities %}
                        <a class="btn btn-success btn-statement"
                           href="{% url 'statement:statement_show' week_offset start_date %}?city={{ city.id }}">Показать (только <b>{{ city.name }}</b>)</a>
                    {% endfor %}
                    <hr>
                    <a class="btn btn-warning btn-statement"
                       href="{% url 'statement:export_xls' week_offset start_date %}">Загрузить .xls</a>
                   {% comment %} <a class="btn btn-warning btn-statement"
                                    href="{% url 'statement:export_xls' week_offset start_date %}?only_users=1">Загрузить .xls (без левой части)</a>
                    {% for city in cities %}
                        <a class="btn btn-warning"
                           href="{% url 'statement:export_xls' week_offset start_date %}?city={{ city.id }}">Загрузить .xls (только {{ city.name }})</a>
                    {% endfor %}{% endcomment %}
                </div>
                <!-- buttons end -->

            </div>
        </div>
    </div>
{% endblock %}

statement/templates/statement/show.html
{% load statement_tags %}
<html>
    <title>Ведомость {{ start_week }} - {{ end_week }}</title>
    <head>
        <style>
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
            td {
                text-align: center;
            }
            tbody td:nth-child(2n - 1) {
                background-color: #00B0F0;
            }
            tbody td:nth-child(2n) {
                background-color: #92CDDC;
            }
            tbody td.club-even {
                background-color:#FFC000;
                font-weight:bold;
                text-align: left;
            }
            tbody td.club-odd {
                background-color:#FFFF00;
                font-weight:bold;
                text-align: left;
            }

            tbody td.manager {
                background-color:#92D050;
            }

            .manager-header {
                vertical-align:bottom;
                background-color:#008000;
                font-weight:bold;
            }

            .club-header {
                vertical-align:bottom;
                background-color:#D09E00;
                font-weight:bold;
            }

            tbody td.drink-name {
                height: 240px;
                white-space: nowrap;
                width: 38px;
                box-sizing: border-box;
                background: white;
            }
            .drink-name nobr {
                transform: /* Magic Numbers */ translate(0px, 100px) /* 45 is really 360 - 45 */ rotate(270deg);
                width: 30px;
                display: inline-block;
            }
            table.drinks-count-table, table.drinks-count-table th, table.drinks-count-table td, table.inside, table.inside th, table.inside td {
                border: none;
            }

            table.drinks-count-table {
                height: 112px;
                table-layout:fixed;
                width: 100%;
            }

            table.drinks-count-table td.cell-drink-count {
                background-color:#FFFF00;
                font-weight:bold;
                width:37px !important;
                text-align:center;
            }

            table.drinks-count-table td.sum-for-club {
                background-color:#FFC000;
                font-weight:bold;
                text-align:center;
                width:78px !important;
            }

            table tbody td.sum-for-header {
                width: 78px;
                background-color: white;
            }

            table.drinks-count-table td.sum-for-coordinator {
                background-color:#92D050;
                text-align:center;
                width:78px !important;
            }

            tr.bottom-row-all td {
                background-color:#E6B8B7;
                font-weight:bold;
            }
            tr.bottom-row-pledge td {
                background-color:#DA9694;
                font-weight:bold;
            }
            tr.bottom-row-penalty td {
                background-color:#FABF8F;
                font-weight:bold;
            }
            tr.bottom-row-penalty-description td {
                background-color:#FABF8F;
                font-weight:bold;
            }
            tr.bottom-row-coordinator td {
                background-color:#B1A0C7;
                font-weight:bold;
            }
            tr.bottom-row-director td {
                background-color:#92CDDC;
                font-weight:bold;
            }
            .admins-salary {
                margin-top:10px;
            }
            .ct-clr {
                color:red;
                text-transform: uppercase;
                display: block;
                margin-top: 5px;
            }
        </style>
    </head>
    <body>
        <h1>{{ start_week }} - {{ end_week }}</h1>
        <table>
            <thead>
                <tr>
                    <td colspan="{{ drinks_count|add:2 }}"></td>
                    <td>Tequilla girl →</td>
                    {% for employee in employees_table_header %}
                        <td>{{ forloop.counter }}. {{ employee.get_full_name }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <td colspan="2"></td>
                    {% for drink_data in drinks_table_header %}
                        {% if drink_data.used %}
                            <td>{{ drink_data.name }}</td>
                        {% endif %}
                    {% endfor %}
                    <td>Менеджер Tequilla girl →</td>
                    {% for employee in employees_table_header %}
                        <td>
                            {% if employee.coordinator %}
                                {{ employee.coordinator.get_full_name }}
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
                <tr>
                    <td class="club-header">Клуб</td>
                    <td class="manager-header">Менеджер клуба</td>
                    {% if drinks_count %}
                        <td colspan="{{ drinks_count }}"></td>
                    {% endif %}
                    <td>Напитки →</td>
                    {% for drinks in header_drinks_for_employee.values %}
                            <td>
                                <table class="inside" style="table-layout: fixed;">
                                    <tr>
                                        {% for drink in drinks  %}
                                            <td class="drink-name">
                                                <nobr>{{ drink }}</nobr>
                                            </td>
                                        {% endfor %}

                                        <td class="sum-for-header">Всего клуб</td>
                                        <td class="sum-for-header">Коорд-р</td>
                                    </tr>
                                </table>
                            </td>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for data in grid %}
                    <tr>
                        <td class="club-{% cycle 'even' 'odd' %}">
                            <span>
                                {{ forloop.counter }}. {{ data.club.name }} {{ data.club.get_address }}
                            </span>
                            <span class="ct-clr">
                                {{ data.club.city.name }}
                            </span>
                        </td>
                        <td class="manager">{{ data.club.coordinator.surname|default_if_none:"" }}</td>
                        {% for price in data.drinks_for_club %}
                            {% if price.used %}
                                <td>{{ price.sum }}</td>
                            {% endif %}
                        {% endfor %}
                        <td></td>
                        {% for info in data.employees_info %}
                            <td>
                            <table class="drinks-count-table" cellpadding="0" cellspacing="0">
                                <tbody>
                                <tr>
                                    {% for drink in info.drinks_list  %}
                                        <td class="cell-drink-count">
                                            {{ drink.count }}
                                        </td>
                                    {% endfor %}
                                    <td class="sum-for-club">{{ info.sum_for_club|floatformat:2  }} р.</td>
                                    <td class="sum-for-coordinator"> {{ info.sum_for_coordinator|floatformat:2 }} р.</td>
                                </tr>
                                </tbody>
                            </table>
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                <tr class="bottom-row-all">
                    <td>ВСЕГО (Перевод Tequilla girl)</td>
                    <td colspan="{{ drinks_count|add:2 }}"></td>
                    {% for info in bottom_prices_for_employee.values %}
                        <td>{{ info.all|floatformat:2 }}</td>
                    {% endfor %}
                </tr>
                <tr class="bottom-row-pledge">
                    <td>Залог Tequilla girl</td>
                    <td colspan="{{ drinks_count|add:2 }}"></td>
                    {% for info in bottom_prices_for_employee.values %}
                        <td>{{ info.pledge }}</td>
                    {% endfor %}
                </tr>
                <tr class="bottom-row-penalty">
                    <td>Штраф</td>
                    <td colspan="{{ drinks_count|add:2 }}"></td>
                    {% for info in bottom_prices_for_employee.values %}
                        <td>{{ info.penalty }}</td>
                    {% endfor %}
                </tr>
                <tr class="bottom-row-penalty-description">
                    <td>Причина штрафа</td>
                    <td colspan="{{ drinks_count|add:2 }}"></td>
                    {% for info in bottom_prices_for_employee.values %}
                        <td>
                            {% for description in info.penalty_description %}
                                {{ description }}<br>
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>
                <tr class="bottom-row-coordinator">
                    <td>Координатор (всего за клубы по каждой Tequilla Girl)</td>
                    <td colspan="{{ drinks_count|add:2 }}"></td>
                    {% for info in bottom_prices_for_employee.values %}
                        <td>{{ info.coordinator|floatformat:2 }} р.</td>
                    {% endfor %}
                </tr>
                <tr class="bottom-row-director">
                    <td>Ермакова (всего за клубы по каждой Tequilla Girl)</td>
                    <td colspan="{{ drinks_count|add:2 }}"></td>
                    {% for info in bottom_prices_for_employee.values %}
                        <td>{{ info.director|floatformat:2 }} р.</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
        <div class="admins-salary">
            {% for coordinator, salary in admins_salary.coordinators.items %}
                <p style="background-color:#FF65A3;font-weight:bold;">Координатор {{ coordinator.get_full_name }} (за все клубы и за всех tequila girls): {{ salary|floatformat:2 }} руб.</p>
            {% endfor %}
            <p style="background-color:#FF4747;font-weight:bold;">Ермакова(за все клубы и за всех tequila girls): {{ admins_salary.director|floatformat:2 }} руб.</p>
        </div>
    </body>
</html>