catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/(?P<item_type>\w+)/$', views.catalog_edit, name='catalog_create'),
    url(r'^edit/(?P<item_type>\w+)/(?P<item_id>\d+)/$', views.catalog_edit, name='catalog_edit'),
    url(r'^remove/(?P<item_type>\w+)/(?P<item_id>\d+)/$', views.catalog_remove, name='catalog_remove'),
    url(r'^filter/(?P<item_type>\w+)/$', views.catalog_filter, name='catalog_filter'),
    url(r'^main_employees/$', views.main_employees, name='main_employees'),
    url(r'^main_penalty_schedule/$', views.main_penalty_schedule, name='main_penalty_schedule'),
    url(r'^week_penalty_schedule/$', views.week_penalty_schedule, name='week_penalty_schedule'),
    url(r'^(?P<item_type>\w+)/$', views.catalog_list, name='catalog_list'),
]

faq/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^main/$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_edit, name='post_create'),
    url(r'^edit/(?P<post_id>\d+)/$', views.post_edit, name='post_edit'),
    url(r'^detail/(?P<post_id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^send_comment/(?P<post_id>\d+)/$', views.send_comment, name='send_comment'),
    url(r'^post_remove/(?P<post_id>\d+)/$', views.post_remove, name='post_remove'),
    url(r'^comment_remove/(?P<comment_id>\d+)/$', views.comment_remove, name='comment_remove'),
    url(r'^comment_update/$', views.comment_update, name='comment_update'),
    url(r'^menu_list/$', views.menu_list, name='menu_list'),
    url(r'^menu_create/$', views.menu_edit, name='menu_create'),
    url(r'^menu_edit/(?P<menu_id>\d+)/$', views.menu_edit, name='menu_edit'),
    url(r'^menu_remove/(?P<menu_id>\d+)/$', views.menu_remove, name='menu_remove'),
    url(r'^get_comment_text/$', views.get_comment_text, name='get_comment_text'),
]

tequilla/urls.py
from django.conf.urls import url, include
from django.http import HttpResponse

from tequilla import settings
from wall.views import index
from extuser.views import user_list, user_detail, user_activity, user_edit
from club.views import club_list
from album.views import user_albums

urlpatterns = [
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    url(r'^profile/', include('extuser.urls', namespace='profile')),
    url(r'^wall/', include('wall.urls', namespace='wall')),
    url(r'^clubs/', include('club.urls', namespace='club')),
    url(r'^album/', include('album.urls', namespace='album')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^tasks/', include('work_calendar.urls', namespace='calendar')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^faq/', include('faq.urls', namespace='faq')),
    url(r'^penalty/', include('penalty.urls', namespace='penalty')),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^uniform/', include('uniform.urls', namespace='uniform')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
    url(r'^statement/', include('statement.urls', namespace='statement')),
    url(r'^weekplan/', include('week_plan.urls', namespace='week_plan')),
    url(r'^dialog/', include('private_message.urls', namespace='pm')),
    url(r'^calculator/', include('calculator.urls', namespace='calc')),
    url(r'^employee/(?P<user_id>\d+)/', user_detail, name='user_detail'),
    url(r'^employee/album/(?P<user_id>\d+)/', user_albums, name='user_albums'),
    url(r'^employee/edit/(?P<user_id>\d+)/', user_edit, name='user_edit'),
    url(r'^employee/auth/(?P<user_id>\d+)/', user_activity, name='user_activity'),
    url(r'^employee/', user_list, name='user_list'),
    url(r'^$', index, name='wall_index'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


class MainEmployees(models.Model):
    file = models.FileField(upload_to='main_employees', blank=True, null=True)

    @staticmethod
    def get_file():
        obj, created = MainEmployees.objects.get_or_create(pk=1)
        return obj


class FakeCity(models.Model):
    name = models.CharField('Название', max_length=255)

catalog/forms.py
from django import forms

from catalog.models import FakeCity


class FakeCityForm(forms.ModelForm):
    class Meta:
        model = FakeCity
        fields = ('name',)

catalog/views.py
import json

import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
import importlib

from django.template.loader import render_to_string
from django.utils import formats
from django.utils.dateparse import parse_date

from catalog.models import MainEmployees
from club.models import DayOfWeek
from penalty.forms import MainPenaltyScheduleForm
from penalty.models import MainPenaltySchedule
from tequilla.decorators import group_required


CATALOG_DATA = {
    'clubtype': {
        'title': 'Типы заведения',
        'new_item_text': 'Добавить новый тип заведения',
        'class_name': 'ClubType',
        'module_name': 'club.models',
        'form_class_name': 'ClubTypeForm',
        'form_module_name': 'club.forms',
        'filters': [
            {'name': 'name__icontains', 'type': 'text', 'prop': 'name', 'label': 'Название'}
        ]
    },
    'metro': {
        'title': 'Станции метро',
        'new_item_text': 'Добавить новую станцию метро',
        'class_name': 'Metro',
        'module_name': 'club.models',
        'form_class_name': 'MetroForm',
        'form_module_name': 'club.forms',
        'filters': [
            {'name': 'id__exact', 'type': 'text', 'prop': 'id', 'label': 'ID'},
            {'name': 'name__icontains', 'type': 'text', 'prop': 'name', 'label': 'Название'},
        ]
    },
    'city': {
        'title': 'Города',
        'new_item_text': 'Добавить новый город',
        'class_name': 'FakeCity',
        'module_name': 'catalog.models',
        'form_class_name': 'FakeCityForm',
        'form_module_name': 'catalog.forms',
        'filters': [
            {'name': 'id__exact', 'type': 'text', 'prop': 'id', 'label': 'ID'},
            {'name': 'name__icontains', 'type': 'text', 'prop': 'name', 'label': 'Название'},
        ]
    },
    'drink': {
        'title': 'Напитки',
        'new_item_text': 'Добавить новый напиток',
        'class_name': 'Drink',
        'module_name': 'club.models',
        'form_class_name': 'DrinkForm',
        'form_module_name': 'club.forms',
        'filters': [
            {'name': 'id__exact', 'type': 'text', 'prop': 'id', 'label': 'ID'},
            {'name': 'name__icontains', 'type': 'text', 'prop': 'name', 'label': 'Название'}
        ]
    },
    'attribute': {
        'title': 'Форма',
        'new_item_text': 'Добавить новую форму',
        'class_name': 'Uniform',
        'module_name': 'uniform.models',
        'form_class_name': 'UniformEditForm',
        'form_module_name': 'uniform.forms',
        'filters': [
            {'name': 'id__exact', 'type': 'text', 'prop': 'id', 'label': 'ID'},
            {'name': 'name__icontains', 'type': 'text', 'prop': 'name', 'label': 'Название'},
            {'name': 'price__exact', 'type': 'text', 'prop': 'price', 'label': 'Цена'},
            {'name': 'num__exact', 'type': 'text', 'prop': 'num', 'label': 'Позиция'},
        ]
    },
    'penaltytype': {
        'title': 'Типы штрафов',
        'new_item_text': 'Добавить новый тип штрафа',
        'class_name': 'PenaltyType',
        'module_name': 'penalty.models',
        'form_class_name': 'PenaltyTypeForm',
        'form_module_name': 'penalty.forms',
        'filters': [
            {'name': 'description__icontains', 'type': 'text', 'prop': 'description', 'label': 'Описание'},
            {'name': 'num__exact', 'type': 'text', 'prop': 'num', 'label': 'Номер'},
            {'name': 'sum__exact', 'type': 'text', 'prop': 'sum', 'label': 'Сумма'},
            {'name': 'dismissal', 'type': 'select', 'prop': 'dismissal', 'label': 'Возможно увольнение'},
        ]
    }
}


def class_for_name(module_name, class_name):
    # load the module, will raise ImportError if module cannot be loaded
    m = importlib.import_module(module_name)
    # get the class, will raise AttributeError if class cannot be found
    c = getattr(m, class_name)
    return c


@login_required
@group_required('director', 'chief', 'coordinator')
def catalog_list(request, item_type):
    if item_type not in CATALOG_DATA:
        raise Http404
    data = CATALOG_DATA[item_type]
    Class = class_for_name(data['module_name'], data['class_name'])
    if item_type == 'drink':
        items = Class.actual_objects.all()
    else:
        items = Class.objects.all()
    return render(
        request,
        'catalog/list.html',
        {
            'data': data,
            'items': items,
            'item_type': item_type,
            'filter_link': reverse('catalog:catalog_filter', kwargs={'item_type': item_type})
        }
    )


@login_required
@group_required('director', 'chief', 'coordinator')
def main_employees(request):
    item = MainEmployees.get_file()
    if request.method == 'POST' and 'employees' in request.FILES:
        item.file = request.FILES['employees']
        item.save()
        messages.add_message(request, messages.INFO, 'Файл успешно загружен')
        return redirect('catalog:main_employees')
    return render(
        request,
        'catalog/main_employees.html',
        {
            'item': item
        }
    )


@login_required
@group_required('director', 'chief', 'coordinator')
def main_penalty_schedule(request):
    items = MainPenaltySchedule.get_settings()
    if request.method == 'POST':
        item_type = request.POST.get('type', MainPenaltySchedule.SCHEDULE_TYPE_CHOICE)
        item, created = MainPenaltySchedule.objects.get_or_create(type=item_type, start_week=None)
        data = {
            'type': item.type,
            'day_of_week': request.POST.get('day_of_week', 0),
            'time': request.POST.get('time', '00:00'),
            'is_active': request.POST.get('is_active', False)
        }
        form = MainPenaltyScheduleForm(instance=item, data=data)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'Информация успешно сохранена')
        return redirect('catalog:main_penalty_schedule')
    forms = [MainPenaltyScheduleForm(instance=item) for item in items]
    return render(
        request,
        'catalog/penalty_schedule.html',
        {
            'forms': forms,
            'work_days': DayOfWeek.objects.all(),
            'title': 'График проставления штрафов по умолчанию'
        }
    )


@login_required
@group_required('director', 'chief', 'coordinator')
def week_penalty_schedule(request):
    week_offset = int(request.GET.get('week', 0))
    start_date = parse_date(request.GET.get('start_date', str(datetime.date.today())))
    date = start_date + datetime.timedelta(week_offset * 7)
    start_week = date - datetime.timedelta(date.weekday())
    end_week = start_week + datetime.timedelta(6)

    items = MainPenaltySchedule.get_settings_by_week(start_week)

    if request.method == 'POST':
        item_type = request.POST.get('type', MainPenaltySchedule.SCHEDULE_TYPE_CHOICE)
        item, created = MainPenaltySchedule.objects.get_or_create(type=item_type, start_week=start_week)
        data = {
            'type': item.type,
            'day_of_week': request.POST.get('day_of_week', 0),
            'time': request.POST.get('time', '00:00'),
            'is_active': request.POST.get('is_active', False)
        }
        form = MainPenaltyScheduleForm(instance=item, data=data)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'Информация успешно сохранена')
        return redirect('catalog:week_penalty_schedule')
    forms = [MainPenaltyScheduleForm(instance=item) for item in items]
    return render(
        request,
        'catalog/penalty_schedule.html',
        {
            'forms': forms,
            'work_days': DayOfWeek.objects.all(),
            'next_week': week_offset + 1,
            'prev_week': week_offset - 1,
            'start_week': start_week,
            'end_week': end_week,
            'week_offset': week_offset,
            'start_date': formats.date_format(start_date, 'Y-m-d'),
            'title': 'График проставления штрафов по неделям (приоритет выше)'
        }
    )


@login_required
@group_required('director', 'chief', 'coordinator')
def catalog_filter(request, item_type):
    if item_type not in CATALOG_DATA:
        data = '%s(%s);' % (request.GET['callback'], json.dumps({'items': ''}))
        return HttpResponse(data, "text/javascript")
    data = CATALOG_DATA[item_type]
    Class = class_for_name(data['module_name'], data['class_name'])
    if 'callback' in request.GET:
        object_list = Class.objects
        filters = [f['name'] for f in data['filters']]
        was_filtered = False
        for filter_name in filters:
            filter_value = request.GET.get(filter_name, '')
            if filter_value:
                filter_pack = {filter_name: filter_value}
                object_list = object_list.filter(**filter_pack)
                was_filtered = True
        if not was_filtered:
            object_list = object_list.all()

        rendered_blocks = {
            'items': render_to_string(
                'catalog/_list.html',
                {'items': object_list, 'item_type': item_type, 'data': data}
            ),
        }
        data = '%s(%s);' % (request.GET['callback'], json.dumps(rendered_blocks))
        return HttpResponse(data, "text/javascript")


@login_required
@group_required('director', 'chief', 'coordinator')
def catalog_edit(request, item_type, item_id=None):
    if item_type not in CATALOG_DATA:
        raise Http404
    data = CATALOG_DATA[item_type]
    Class = class_for_name(data['module_name'], data['class_name'])
    Form = class_for_name(data['form_module_name'], data['form_class_name'])
    try:
        item = Class.objects.get(id=item_id)
    except Class.DoesNotExist:
        item = Class()

    if request.method == 'POST':

catalog/templates/catalog/_list.html
{% for item in items %}
    <tr>
        {% for filter in data.filters %}
            <td>
                {% if filter.prop == 'id' %}
                    {{ item.id }}
                {% elif filter.prop == 'name' %}
                    {{ item.name }}
                {% elif filter.prop == 'description' %}
                    {{ item.description }}
                {% elif filter.prop == 'num' %}
                    {{ item.num }}
                {% elif filter.prop == 'sum' %}
                    {{ item.sum }}
                {% elif filter.prop == 'price' %}
                    {{ item.price }}
                {% elif filter.prop == 'price_for_sale' %}
                    {{ item.price_for_sale }}
                {% elif filter.prop == 'price_in_bar' %}
                    {{ item.price_in_bar }}
                {% elif filter.prop == 'dismissal' %}
                    {% if item.dismissal %}Да{% else %}Нет{% endif %}
                {% endif %}
            </td>
        {% endfor %}
        <td style="width: 115px;">
            <a href="{% url 'catalog:catalog_edit' item_type item.id %}" class="btn-warning btn">
                <i class="fa fa-edit"></i>
            </a>
            <a href="{% url 'catalog:catalog_remove' item_type item.id %}" class="btn-danger btn remove-link">
                <i class="fa fa-remove"></i>
            </a>
        </td>
    </tr>
{% empty %}
    <tr>
        <td colspan="5">Объекты не найдены.</td>
    </tr>
{% endfor %}

catalog/templates/catalog/edit.html
{% extends 'base.html' %}

{% block title %}
    {{ data.title }}: {% if item.id %}Редактирование{% else %}Добавление{% endif %}
{% endblock %}

{% block additional_js %}
    <script type="text/javascript">
        $(function() {
            $('form input, form textarea').not(':checkbox').addClass('form-control');
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ data.title }}: {% if item.id %}Редактирование{% else %}Добавление{% endif %}</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>
                    <form data-parsley-validate=""
                          class="form-horizontal form-label-left"
                          action="{% if item.id %}{% url 'catalog:catalog_edit' item_type item.id %}{% else %}{% url 'catalog:catalog_create' item_type %}{% endif %}"
                          method="POST">
                        {% if messages %}
                            <p class="alert alert-success fade in">
                                {% for message in messages %}
                                    <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span><br>
                                {% endfor %}
                            </p>
                        {% endif %}
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group{% if field.errors %} bad{% endif %}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                                {{ field.label }} {% if field.field.required %}<span class="required">*</span>{% endif %}
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ field }}
                                {% if field.errors %}
                                    <ul class="parsley-errors-list" id="parsley-id-{{ forloop.counter }}">
                                         {% for error in field.errors %}
                                            <li>{{ error|escape }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/list.html
{% extends 'base.html' %}

{% block title %}{{ data.title }}{% endblock %}

{% block additional_js %}
    <script type="text/javascript">

        function getNewContent() {
            // сбор данных фильтров
            var form = $('#filters-form');
                filters = '?' + form.serialize();

            // запрос нового контента
            $.ajax({
                url: '{{ filter_link }}' + filters,
                type: 'GET',
                dataType: 'jsonp',
                crossDomain: true,
                success: function (data) {
                    $('#list-content').html(data['items']);
                }
            });
        }

        $(function() {
            $('.remove-link').on('click', function() {
                return confirm('Подтвердите удаление');
            });

            $('.filter-input').on('keyup', function() {
                getNewContent();
            });
        });
    </script>
{% endblock %}

{% block content %}
    <a href="{% url 'catalog:catalog_create' item_type %}" class="btn btn-info">{{ data.new_item_text }}</a>
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>{{ data.title }}</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table class="table table-bordered table-striped">
                <tr>
                    <form id="filters-form">
                        {% for filter in data.filters %}
                            <th>
                                <div>
                                    {{ filter.label }}
                                </div>
                                {% if filter.type == 'text' %}
                                    <input type="text" name="{{ filter.name }}" class="form-control filter-input">
                                {% endif %}
                            </th>
                        {% endfor %}
                    </form>
                    <th>Операции</th>
                </tr>
                <tbody id="list-content">
                    {% include 'catalog/_list.html' %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/main_employees.html
{% extends 'base.html' %}

{% block title %}
    Основной состав
{% endblock %}

{% block additional_css %}
    <style type="text/css">
        input[type=file] {
            display: inline-block;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Основной состав</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>
                    <form data-parsley-validate=""
                          class="form-horizontal form-label-left"
                          action="{% url 'catalog:main_employees' %}"
                          enctype="multipart/form-data"
                          method="POST">
                        {% if messages %}
                            <p class="alert alert-success fade in">
                                {% for message in messages %}
                                    <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span><br>
                                {% endfor %}
                            </p>
                        {% endif %}
                        {% csrf_token %}
                        {% if item.file %}
                            <a target="_blank" href="{{ item.file.url }}">{{ item.file.name }}</a>
                        {% else %}
                            Файл еще не загружен.
                        {% endif %}
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="file" class="btn btn-warning" name="employees" value="Загрузить другой">
                                <button type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/penalty_schedule.html
{% extends 'base.html' %}
{% load extuser_tags %}
{% load staticfiles %}

{% block title %}
    {{ title }}
{% endblock %}

{% block additional_css %}
    <style type="text/css">
        select {
            margin-right: 25px;
            width: 100% !important;
        }
        .btn {
            margin-bottom: 0;
        }
    </style>
{% endblock %}


{% block additional_js %}
    <script type="text/javascript" src="{% static 'js/jquery.timepicker.min.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            // выбор недели по дате
            $('#calendar').daterangepicker(calendar_options);
            $('#calendar').on('apply.daterangepicker', function(e, picker) {
                var date = picker.startDate.format('YYYY-MM-DD');
                location = '{% url 'catalog:week_penalty_schedule' %}?start_date=' + date;
            });

            var timepicker_options = { 'timeFormat': 'H:i', 'step': 30 };
            $('input[name="time"]').timepicker(timepicker_options);
        });
    </script>
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ title }}
                        {% if start_week %}
                            <small>{{ start_week }} - {{ end_week }}</small>
                        {% endif %}
                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    {% if start_week %}
                        <a href="?week={{ prev_week }}&start_date={{ start_date }}">
                            <button class="btn"><i class="fa fa-long-arrow-left"></i> Предыдущая неделя</button>
                        </a>
                        <a href="?week={{ next_week }}&start_date={{ start_date }}">
                            <button class="btn">Следующая неделя <i class="fa fa-long-arrow-right"></i></button>
                        </a>
                        <div class="small-margin-top">
                            {% if perms.extuser.can_edit_users %}
                                <button class="btn btn-primary" id="calendar">Выбрать неделю по дате</button>
                            {% endif %}
                    </div>
                    {% endif %}
                        {% if messages %}
                            <p class="alert alert-success fade in">
                                {% for message in messages %}
                                    <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span><br>
                                {% endfor %}
                            </p>
                        {% endif %}
                        {% for form in forms %}
                            <div class="small-margin-top">
                                <form data-parsley-validate=""
                                  class="form-horizontal form-label-left small-margin-top"
                                  action="{% if start_week %}{% url 'catalog:week_penalty_schedule' %}?week={{ week_offset }}{% else %}{% url 'catalog:main_penalty_schedule' %}{% endif %}"
                                  method="POST">
                                    {% csrf_token %}
                                    {% for field in form %}
                                        {% if field.name != 'type' %}
                                            <div class="form-group">
                                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ field.name }}">
                                                {{ field.label }}
                                            </label>
                                            <div class="col-md-3 col-sm-3 col-xs-12">
                                                {{ field }}
                                            </div>
                                        </div>
                                        {% else %}
                                            <div class="form-group">
                                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ field.name }}">
                                                {{ field.label }}
                                            </label>
                                            <div class="col-md-3 col-sm-3 col-xs-12">
                                                {{ field }}
                                                <span style="margin-top: 7px; display: inline-block;">{{ field|display }}</span>
                                            </div>
                                        </div>
                                        {% endif %}
                                        {% endfor %}
                                        <div class="form-group">
                                            <input type="submit" class="btn btn-success col-md-offset-2" value="Сохранить">
                                        </div>
                                </form>
                            </div>
                            {% if not forloop.last %}<hr>{% endif %}
                        {% endfor %}

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}